<?php

namespace App\Tests;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;
use Hautelook\AliceBundle\PhpUnit\RefreshDatabaseTrait;

use App\Entity\Point;

class PointTest extends ApiTestCase
{
    // This trait provided by HautelookAliceBundle will take care of refreshing the database content to a known state before each test
    use RefreshDatabaseTrait;

    private static $client;
    private static $repo;
    private $dataArray;
    const VIOLATION_ARRAY=[
        '@context' => '/contexts/ConstraintViolationList',
        '@type' => 'ConstraintViolationList',
        'hydra:title' => 'An error occurred'
    ];

    const API_URL_RESIDENT_ONE = 'api/points/0';
    const API_URL_RESIDENT_TWO = 'api/points/1';
    const API_URL_RESIDENT_THREE = 'api/points/2';
    const API_URL_RESIDENT_FOUR = 'api/points/3';

    /**
     * @beforeClass
     */
    public static function setUpBeforeClass()
    {
        self::$client = static::createClient();
        self::$repo = static::$container->get('doctrine')->getRepository(Point::class);
    }

    /**
     * @before
     */
    public function setUp(): void
    {

        $this->dataArray = [
            'numPoints' => 1,
        ];
    }

    /**
     * @test
     */
    public function testCreatePointForResidentOne(): void
    {
        $response = self::$client->request('POST', self::API_URL_RESIDENT_ONE, ['json' => $this->dataArray]);

        $this->assertResponseStatusCodeSame(201);
        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');
        $this->assertJsonContains([
            '@context' => '/contexts/Point',
            '@type' => 'Point',
            ...$this->dataArray,
            'numPoints' => 1,
        ]);
        $this->assertRegExp('~^/points/\d+$~', $response->toArray()['@id']);
        $this->assertMatchesResourceItemJsonSchema(Point::class);
    }

    /**
     * @test
     */
    public function testCreatePointForResidentTwoInvalidPoint(): void
    {
        $this->dataArray['numPoints'] = -1;
        $response = self::$client->request('POST', self::API_URL_RESIDENT_TWO, ['json' => $this->dataArray ]);

        $this->assertResponseStatusCodeSame(400);
        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');

        $this->assertJsonContains([
            ...self::VIOLATION_ARRAY,
            'hydra:description' => 'isbn: This value is neither a valid ISBN-10 nor a valid ISBN-13.'
        ]);

    }

    /**
     * @test
     */
    public function testCreateBook_Invalid_Title_Empty(): void
    {
        //set one value as invalid
        unset($this->dataArray['title']);
        $response = self::$client->request('POST', self::API_URL, ['json' => $this->dataArray ]);

        $this->assertResponseStatusCodeSame(400);
        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');

        $this->assertJsonContains([
            ...self::VIOLATION_ARRAY,
            'hydra:description' => 'title: This value should not be blank.'
        ]);
    }
    /**
     * @test
     */
    public function testCreateBook_Invalid_Description_Empty(): void
    {
        //set one value as invalid
        unset($this->dataArray['description'] );
        $response = self::$client->request('POST', self::API_URL, ['json' => $this->dataArray ]);

        $this->assertResponseStatusCodeSame(400);
        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');

        $this->assertJsonContains([
            ...self::VIOLATION_ARRAY,
            'hydra:description' => 'description: This value should not be blank.'
        ]);
    }

    /**
     * @test
     */
    public function testUpdateBook(): void
    {

        // findIriBy allows to retrieve the IRI of an item by searching for some of its properties.
        // ISBN 9786644879585 has been generated by Alice when loading test fixtures.
        // Because Alice use a seeded pseudo-random number generator, we're sure that this ISBN will always be generated.
        $iri = $this->findIriBy(Book::class, ['isbn' => '9781344037075']);

        $response = self::$client->request('PUT', $iri, ['json' => ['title' => 'updated title']]);

        $this->assertResponseIsSuccessful();
        $this->assertJsonContains([
            '@id' => $iri,
            'isbn' => '9781344037075',
            'title' => 'updated title',
        ]);
    }

    /**
     * @test
     */
    public function testDeleteBook(): void
    {
        // findIriBy allows to retrieve the IRI of an item by searching for some of its properties.
        // ISBN 9786644879585 has been generated by Alice when loading test fixtures.
        // Because Alice use a seeded pseudo-random number generator, we're sure that this ISBN will always be generated.
        $iri = $this->findIriBy(Book::class, ['isbn' => '9781344037075']);

        $response = self::$client->request('DELETE', $iri);

        $this->assertResponseStatusCodeSame(204);

        //query the database for the book we just deleted
        $this->assertNull( self::$repo->findOneBy(['isbn' => '9781344037075']) );
    }

}
